# Generated by Django 2.1.7 on 2019-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_file',
            field=models.ImageField(
                blank=True, null=True, upload_to='article/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(
                related_name='posts', to='post.ImagePost'),
        ),
    ]
