# Generated by Django 2.1.7 on 2019-03-22 20:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='posts_category', to='post.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(
                related_name='posts_photo', to='post.ImagePost'),
        ),
    ]
